### ISSUE TITLE
[Jira] Unable to upload big file (150 MB) as an attachment, getting timed out error

### ISSUE THREAD

**Issue by akashp1712** [atlassian-api/atlassian-python-api#1006]
Hi Team,

I'm trying to use the API: **jira.add_attachment()** and not able to attach big file **(~150 MB)**
The script keeps getting timed out even if having fast internet connection.

Following is the stack trace, it would be great if some one can suggest a way to increase the time out duration.

`Traceback (most recent call last):
  File "/Users/akashnew/workplace/streamlit/app1/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/akashnew/workplace/streamlit/app1/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/akashnew/workplace/streamlit/app1/venv/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1079, in _send_output
    self.send(chunk)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1001, in send
    self.sock.sendall(data)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
**socket.timeout: The write operation timed out**

...
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
**urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))**

...
  File "/Users/akashnew/workplace/streamlit/app1/venv/lib/python3.9/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
**requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out'))**
`

**Comment by gonchik** [comment]
Hi! 
Looks like you need check the limits of upload on Jira side.

**Comment by akashp1712** [comment]
Hi @gonchik, Thanks for responding.
I've verified the attachment limit, it was higher than 150MB, However, I've solved the issue by increasing **timeout** duration to 20 minutes.

This is good to close.
