### ISSUE TITLE
[Bitbucket Server] Fork Repository for different project

### ISSUE THREAD

**Issue by srshiva** [atlassian-api/atlassian-python-api#1043]
Function fork_repository_new_project in bitbucket module is throwing error while trying to create.

Traceback (most recent call last):
  File "venv\lib\site-packages\atlassian\rest_client.py", line 400, in raise_for_status
    j.get("errorMessages", list()) + [k + ": " + v for k, v in j.get("errors", dict()).items()]
AttributeError: 'list' object has no attribute 'items'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "venv\lib\site-packages\atlassian\bitbucket\__init__.py", line 893, in fork_repository_new_project
    print(url,data=body)
  File "venv\lib\site-packages\atlassian\rest_client.py", line 310, in post
    response = self.request(
  File "venv\lib\site-packages\atlassian\rest_client.py", line 243, in request
    self.raise_for_status(response)
  File "venv\lib\site-packages\atlassian\rest_client.py", line 403, in raise_for_status
    response.raise_for_status()
  File "venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url:

**Comment by srshiva** [comment]
data = bitbucket.fork_repository_new_project(
    project_key="PROJ1",
    repository_slug="repo1",
    new_repository_slug="rep02",
    new_project_key="PROJ2"
)

This is working as expected but not the bitbucket.fork_repository_new_project("PROJ1", "repo1", "rep02","PROJ2")

**Comment by Spacetown** [comment]
The function signature is:
```python
def fork_repository_new_project(self, project_key, repository_slug, new_project_key, new_repository_slug):
```
You should change the order of the last two arguments.

**Comment by srshiva** [comment]
Thanks @Spacetown
