### ISSUE TITLE
[X-ray] HttpError

### ISSUE THREAD

**Issue by lozik4** [atlassian-api/atlassian-python-api#1059]
Traceback (most recent call last):
  File "/Users/qa/Documents/projName/autotests/sandbox/xRay.py", line 38, in <module>
    main()
  File "/Users/qa/Documents/projName/autotests/sandbox/xRay.py", line 27, in main
    res = xr.get_tests(['projName-7132'])
  File "/Users/qa/Documents/show4me/autotests/venv/lib/python3.9/site-packages/atlassian/xray.py", line 21, in get_tests
    return self.get(url)
  File "/Users/qa/Documents/show4me/autotests/venv/lib/python3.9/site-packages/atlassian/rest_client.py", line 271, in get
    response = self.request(
  File "/Users/qa/Documents/show4me/autotests/venv/lib/python3.9/site-packages/atlassian/rest_client.py", line 243, in request
    self.raise_for_status(response)
  File "/Users/qa/Documents/show4me/autotests/venv/lib/python3.9/site-packages/atlassian/rest_client.py", line 405, in raise_for_status
    raise HTTPError(error_msg, response=response)
requests.exceptions.HTTPError

Response was returned but error printing to in console

**Comment by sbor23** [comment]
Can confirm, same issue here.
```
  File "/app/dataserver/utils/try_and_rollback.py", line 91, in execute
    res = command.execute()
  File "/app/dataserver/utils/data_importer.py", line 319, in execute
    client.update_issue_field(test, user)
  File "/usr/local/lib/python3.9/site-packages/atlassian/jira.py", line 1029, in update_issue_field
    return self.put("{base_url}/{key}".format(base_url=base_url, key=key), data={"fields": fields})
  File "/usr/local/lib/python3.9/site-packages/atlassian/rest_client.py", line 340, in put
    response = self.request(
  File "/usr/local/lib/python3.9/site-packages/atlassian/rest_client.py", line 243, in request
    self.raise_for_status(response)
  File "/usr/local/lib/python3.9/site-packages/atlassian/rest_client.py", line 405, in raise_for_status
    raise HTTPError(error_msg, response=response)
requests.exceptions.HTTPError: reporter: Field 'reporter' cannot be set. It is not on the appropriate screen, or unknown.
assignee: Field 'assignee' cannot be set. It is not on the appropriate screen, or unknown.
```

```
ipdb> response.request.__dict__
{'_body_position': None,
 '_cookies': <RequestsCookieJar[Cookie(version=0, name='JSESSIONID', value='xxx', port=None, port_specified=False, domain='jira.xxx.com', domain_specified=False, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=None, discard=True, comment=None, comment_url=None, rest={'HttpOnly': None}, rfc2109=False), Cookie(version=0, name='atlassian.xsrf.token', value='xxx', port=None, port_specified=False, domain='jira.xxx.com', domain_specified=False, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=None, discard=True, comment=None, comment_url=None, rest={}, rfc2109=False)]>,
 'body': '{"fields": {"assignee": {"name": "xxx"}, '
         '"reporter": {"name": "xxx"}}}',
 'headers': {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Cookie': 'xxx', 'Content-Length': '106', 'Authorization': 'Basic xxx'},
 'hooks': {'response': []},
 'method': 'PUT',
 'url': 'https://jira.xxx.com/rest/api/2/issue/TAUT-243'}
```
However the response is NOT returned. At the same time the change IS applied in Jira... So I suspect a Xray/Jira bug.

**Comment by gonchik** [comment]
it has been fixed long time ago
