### ISSUE TITLE
Bitbucket Cloud not working

### ISSUE THREAD

**Issue by hyunlee1o** [atlassian-api/atlassian-python-api#1069]
This code is not working. Seems like Cloud works and Bitbucket doesn't. 
```
oauth2 = {
    'client_id': os.getenv('client-id'),
    'token': {
        'token_type': 'Bearer',
        'access_token': os.getenv('access-token')
    },
}

cloud = Cloud(
    url="https://api.bitbucket.org/",
    oauth2=oauth2,
    cloud=True,
    # advanced_mode=True
)

res = cloud.get("repositories/test")

bitbucket = Bitbucket(
    url="https://api.bitbucket.org/",
    oauth2=oauth2,
    cloud=True,
)

p = list(bitbucket.project_list())
```
The error i get is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.cache/pypoetry/virtualenvs/autogit-qXb98hrH-py3.10/lib/python3.10/site-packages/atlassian/bitbucket/base.py", line 59, in _get_paged
    response = self.get(url, trailing=trailing, params=params, data=data, flags=flags, absolute=absolute)
  File "/home/user/.cache/pypoetry/virtualenvs/autogit-qXb98hrH-py3.10/lib/python3.10/site-packages/atlassian/rest_client.py", line 273, in get
    "GET",
  File "/home/user/.cache/pypoetry/virtualenvs/autogit-qXb98hrH-py3.10/lib/python3.10/site-packages/atlassian/rest_client.py", line 245, in request
    return response
  File "/home/user/.cache/pypoetry/virtualenvs/autogit-qXb98hrH-py3.10/lib/python3.10/site-packages/atlassian/rest_client.py", line 407, in raise_for_status
    else:
requests.exceptions.HTTPError
```
I made a print so that the url that is called gets printed and i got this:
`url => https://api.bitbucket.org/2.0/projects`

**Comment by Spacetown** [comment]
You are comparing apples with pears. The URLs are different for both calls, you should use the same endpoint for compare.

The traceback is confusing since some calls (e.g. `_get_paged`) are missing.

**Comment by hyunlee1o** [comment]
I have tried with the same endpoint and the error is the same.
```
https://api.bitbucket.org/2.0/repositories/test
https://api.bitbucket.org/repositories/test
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
File ~/Documentos/autogit/src/test.py:95
     87 res = cloud.get("repositories/test")
     89 bitbucket = Bitbucket(
     90     url="https://api.bitbucket.org/",
     91     oauth2=oauth2,
     92     cloud=True,
     93 )
---> 95 p = bitbucket.get("repositories/test")
     96 # p = list(bitbucket.project_list())

File ~/.cache/pypoetry/virtualenvs/autogit-qXb98hrH-py3.10/lib/python3.10/site-packages/atlassian/rest_client.py:272, in AtlassianRestAPI.get(self, path, data, flags, params, headers, not_json_response, trailing, absolute, advanced_mode)
    247 def get(
    248     self,
    249     path,
   (...)
    257     advanced_mode=False,
    258 ):
    259     """
    260     Get request based on the python-requests module. You can override headers, and also, get not json response
    261     :param path:
   (...)
    270     :return:
    271     """
--> 272     response = self.request(
    273         "GET",
    274         path=path,
    275         flags=flags,
    276         params=params,
    277         data=data,
    278         headers=headers,
    279         trailing=trailing,
    280         absolute=absolute,
    281     )
    282     if self.advanced_mode or advanced_mode:
    283         return response

File ~/.cache/pypoetry/virtualenvs/autogit-qXb98hrH-py3.10/lib/python3.10/site-packages/atlassian/rest_client.py:244, in AtlassianRestAPI.request(self, method, path, data, json, flags, params, headers, files, trailing, absolute)
    241 if self.advanced_mode:
    242     return response
--> 244 self.raise_for_status(response)
    245 return response

File ~/.cache/pypoetry/virtualenvs/autogit-qXb98hrH-py3.10/lib/python3.10/site-packages/atlassian/rest_client.py:406, in AtlassianRestAPI.raise_for_status(self, response)
    404         response.raise_for_status()
    405     else:
--> 406         raise HTTPError(error_msg, response=response)
    407 else:
    408     response.raise_for_status()

HTTPError: 

In [1]: bitbucket.project_list()
Out[1]: <generator object BitbucketBase._get_paged at 0x7fc556a78270>

```

**Comment by Spacetown** [comment]
Now I get it (examples with import statement would help):
```python
import os
from atlassian.bitbucket import Cloud
from atlassian.bitbucket import Bitbucket

oauth2 = {
    'client_id': os.getenv('client-id'),
    'token': {
        'token_type': 'Bearer',
        'access_token': os.getenv('access-token')
    },
}

cloud = Cloud(
    url="https://api.bitbucket.org/",
    oauth2=oauth2,
    cloud=True,
    # advanced_mode=True
)

res = cloud.get("repositories/test")

bitbucket = Bitbucket(
    url="https://api.bitbucket.org/",
    oauth2=oauth2,
    cloud=True,
)

p = bitbucket.get("repositories/test")
```
You're using the object in a wrong way by using directly the `GET` request of the base class which works for the `Cloud` since the API version is added to the URL (`/2.0`) in the `__init__`. In the Bitbucket the functions always adds the version on it's own by calling following function:
https://github.com/atlassian-api/atlassian-python-api/blob/96e0cd19fe131d6f29217e61378e7f2bd0f22199/atlassian/rest_client.py#L164-L169 
The correct usage is:

```python
res = list(cloud.workspaces.get("test").repositories.each())
p = list(bitbucket.get_repositories("test"))  # marked as deprecated
```

**Comment by hyunlee1o** [comment]
Thank you a lot @Spacetown. I had problems getting started with the documentation.
I think a more curated documentation would have helped me not getting stuck on this case.
Have a nice day :)

**Comment by Spacetown** [comment]
For the OO interface you can also check the tests (tests/test_bitbucket_cloud_oo.py) for examples.

**Comment by gonchik** [comment]
@hyunlee1o  if you see some improvement a pull request more welcome :)

**Comment by hyunlee1o** [comment]
I will take a look.
I am good at making accesibile tutorials and stuff. So yeah.
