### ISSUE TITLE
"def fork_repository_new_project" issue

### ISSUE THREAD

**Issue by Kevin-Palmerini** [atlassian-api/atlassian-python-api#1146]
Hello there!
I would like to have an operative python simple script to use Bitbucket in order to execute the fork of a repository from a project to an other existing project. It exists a function to do so: in "<path_to_python_site_packages>/atlassian/bitbucket/__init__.py" with the function name "fork_repository_new_project". 
In the past i had already fixed this issue, but I couldn't anymore.
Could you please help me?
I urgently need your support for a customer!

**Comment by Spacetown** [comment]
What doesn't work? Error message?

**Comment by Kevin-Palmerini** [comment]
This is the error message that I get:
`{'type': 'error', 'error': {'message': 'Resource not found', 'detail': "There is no API hosted at this URL.\n\nFor information about our API's, please refer to the documentation at: https://developer.atlassian.com/bitbucket/api/2/reference/"}}
https://api.bitbucket.org/
Traceback (most recent call last):
  File "C:\Railab\Useful_python_scripts\TestBitbucketAPI\Add_repository_template_in_existing_project.py", line 157, in <module>
    data = BITBUCKET.fork_repository_new_project(template_project_KEY, template_repository_SLUG, project_KEY, creating_repository_SLUG)
  File "C:\Users\Kevin Palmerini\AppData\Local\Programs\Python\Python39\lib\site-packages\atlassian\bitbucket\__init__.py", line 922, in fork_repository_new_project
    return self.post(url, data=body)
  File "C:\Users\Kevin Palmerini\AppData\Local\Programs\Python\Python39\lib\site-packages\atlassian\rest_client.py", line 337, in post
    response = self.request(
  File "C:\Users\Kevin Palmerini\AppData\Local\Programs\Python\Python39\lib\site-packages\atlassian\rest_client.py", line 261, in request
    self.raise_for_status(response)
  File "C:\Users\Kevin Palmerini\AppData\Local\Programs\Python\Python39\lib\site-packages\atlassian\rest_client.py", line 450, in raise_for_status
    raise HTTPError(error_msg, response=response)
requests.exceptions.HTTPError`

**Comment by Kevin-Palmerini** [comment]
I'm not familiar with activate verbose logging..
Could you please share with me the steps in order to activate it and how to check the used URL?
Thank you very much!

**Comment by Kevin-Palmerini** [comment]
Considering the called function:
`def fork_repository_new_project(
        self,
        project_key,
        repository_slug,
        new_project_key,
        new_repository_slug,
    ):
        """
        Forks a repository to a separate project.
        :param project_key: Origin Project Key
        :param repository_slug: Origin repository slug
        :param new_project_key: Project Key of target project
        :param new_repository_slug: Target Repository slug
        :return:
        """
        url = self._url_repo(project_key, repository_slug)
        print(url)
        body = {}
        if new_repository_slug is not None and new_project_key is not None:
            body["name"] = new_repository_slug
            body["project"] = {"key": new_project_key}
        return self.post(url, data=body)`

the URL that I print is the following one:
`/2.0/projects/R9990/repos/project-template/`

**Comment by Kevin-Palmerini** [comment]
Re-running the code:
`[2023-03-30 15:14:24] [DEBUG] curl --silent -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' --data '"{\"name\": \"r0036_GUI_ChatGPT_demo\", \"project\": {\"key\": \"r0036_chatgpt\"}}"' 'https://api.bitbucket.org/2.0/projects/R9990/repos/project-template'
[2023-03-30 15:14:24] [DEBUG] Starting new HTTPS connection (1): api.bitbucket.org:443
[2023-03-30 15:14:25] [DEBUG] https://api.bitbucket.org:443 "POST /2.0/projects/R9990/repos/project-template HTTP/1.1" 404 243
[2023-03-30 15:14:25] [DEBUG] HTTP: POST /2.0/projects/R9990/repos/project-template/ -> 404 Not Found
[2023-03-30 15:14:25] [DEBUG] HTTP: Response text -> {"type": "error", "error": {"message": "Resource not found", "detail": "There is no API hosted at this URL.\n\nFor information about our API's, please refer to the documentation at: https://developer.atlassian.com/bitbucket/api/2/reference/"}}`

**Comment by Spacetown** [comment]
Are you using bitbucket server or cloud? 
The requested URL seems to be BB server (https://developer.atlassian.com/server/bitbucket/rest/v808/api-group-project/#api-api-latest-projects-projectkey-repos-repositoryslug-post) but the link in the error message points to the CC cloud API (https://developer.atlassian.com/bitbucket/api/2/reference/).

**Comment by gonchik** [comment]
@Kevin-Palmerini  do you use Bitbucket Cloud?

**Comment by Spacetown** [comment]
@gonchik It seems so if you take a look at the url (https://developer.atlassian.com/cloud/bitbucket/rest/api-group-repositories/#api-repositories-workspace-repo-slug-forks-post).
