### ISSUE TITLE
confluence.export_page() doesn't work with 3.37.0

### ISSUE THREAD

**Issue by flyisland** [atlassian-api/atlassian-python-api#1172]
In version 3.36.0, the confluence.export_page() function worked properly. 

However, after upgrading to version 3.37.0, errors occurred, such as the one shown below. Upon further investigation, I noticed that the return code for `GET /services/api/v1/task/3521019921/progress` was 200 in version 3.36.0.

```
INFO:atlassian.confluence:Check if export task has completed.
DEBUG:atlassian.rest_client:curl --silent -X GET -H 'Content-Type: application/json' -H 'Accept: application/json'  'https://sol-jira.atlassian.net/wiki/services/api/v1/task/3521019921/progress'
DEBUG:urllib3.connectionpool:https://{my-company-domain}.atlassian.net:443 "GET /wiki/services/api/v1/task/3521019921/progress HTTP/1.1" 404 132
DEBUG:atlassian.rest_client:HTTP: GET /services/api/v1/task/3521019921/progress -> 404 Not Found
DEBUG:atlassian.rest_client:HTTP: Response text -> {"timestamp":1684831098818,"path":"/api/v1/task/3521019921/progress","status":404,"error":"Not Found","requestId":"6b6822fd-205066"}
ERROR:atlassian.confluence:'message'
Traceback (most recent call last):
```

**Comment by gonchik** [comment]
Hi @flyisland , 
could you check on the last version ? 
Cheers,
GT

**Comment by DavidHe1127** [comment]
Same issue here with error 

```
Traceback (most recent call last):
  File "something.py", line 29, in <module>
    pdf = confluence.export_page(page_id)
  File "/usr/local/lib/python3.8/site-packages/atlassian/confluence.py", line 2460, in export_page
    return self.get_page_as_pdf(page_id)
  File "/usr/local/lib/python3.8/site-packages/atlassian/confluence.py", line 2439, in get_page_as_pdf
    raise ApiNotFoundError("Failed to export page as PDF", reason="Failed to get download PDF url.")
atlassian.errors.ApiNotFoundError: Failed to export page as PDF


```

**Comment by gonchik** [comment]
Hm, changes have been made.

**Comment by gonchik** [comment]
Let me reproduce it

**Comment by gonchik** [comment]
@flyisland  I did not reproduce it. 
we can try to connect in discord
https://discord.com/channels/756142204761669743/756142204761669746

**Comment by parsely1231** [comment]
Hi.
This error is probably due to an older version of PDF export running. 
For example, if IP address restrictions are enabled, older versions of PDF exports will work.
ref) https://support.atlassian.com/confluence-cloud/docs/cases-where-pdf-export-may-revert-to-legacy-exporter/

In the new version of pdf export, taskID is in uuID format, whereas in older version it is numeric.
Unfortunately, it seems that the old version of tasks cannot be retrieved with the new API `services/api/v1/task`.

Therefore, I would suggest checking the format of the taskID and if it is a numeric type, use the old API(runningtaskxml.action) to fetch the progress.

**Comment by gonchik** [comment]
it has been fixed
