### ISSUE TITLE
[Bitbucket] [bug] Authorization header gets lost and all methods result in 403

### ISSUE THREAD

**Issue by davidmorabito** [atlassian-api/atlassian-python-api#1194]
### Environment

OS: macOS 13.4
Platform: M1

```
$ venv/bin/python --version
Python 3.11.4
```
```
$ cat venv/lib/python3.11/site-packages/requests/__version__.py
# .-. .-. .-. . . .-. .-. .-. .-.
# |(  |-  |.| | | |-  `-.  |  `-.
# ' ' `-' `-`.`-' `-' `-'  '  `-'

__title__ = "requests"
__description__ = "Python HTTP for Humans."
__url__ = "https://requests.readthedocs.io"
__version__ = "2.28.2"
__build__ = 0x022802
__author__ = "Kenneth Reitz"
__author_email__ = "me@kennethreitz.org"
__license__ = "Apache 2.0"
__copyright__ = "Copyright Kenneth Reitz"
__cake__ = "\u2728 \U0001f370 \u2728"
```
```
$ cat venv/lib/python3.11/site-packages/urllib3/_version.py
# This file is protected via CODEOWNERS
__version__ = "1.26.15"
```
```
$ cat requirements.txt
atlassian-python-api==3.39.0
```

##### test.py
```python
from atlassian import Bitbucket

bitbucket_url = "https://bitbucket.com"
bitbucket_token = "super-secret-token"

bitbucket = Bitbucket(
    url=bitbucket_url,
    token=bitbucket_token,
    timeout=30
)

bitbucket.get_users()
```

### Error

```python
$ venv/bin/python test.py
Traceback (most recent call last):
  File "venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/lib/python3.11/site-packages/atlassian/rest_client.py", line 472, in raise_for_status
    j = response.json()
        ^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    bitbucket.get_users()
  File "venv/lib/python3.11/site-packages/atlassian/bitbucket/__init__.py", line 111, in get_users
    return self.get(url, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/atlassian/rest_client.py", line 285, in get
    response = self.request(
               ^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/atlassian/rest_client.py", line 257, in request
    self.raise_for_status(response)
  File "venv/lib/python3.11/site-packages/atlassian/rest_client.py", line 485, in raise_for_status
    response.raise_for_status()
  File "venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://bitbucket.com/rest/api/1.0/users?limit=25
```

### Debug

When debugging, I can see the *Authorization* header is never passed to requests in order to make the call

`venv/lib/python3.11/site-packages/atlassian/rest_client.py:82`
After Bitbucket instance creation, the authorization header is present inside the session object:

<img width="2168" alt="Screenshot 2023-06-29 at 00 40 08" src="https://github.com/atlassian-api/atlassian-python-api/assets/1463733/6ea14445-67f2-4288-811e-2305e7655519">

`venv/lib/python3.11/site-packages/atlassian/rest_client.py:239`
The Authorization header never reaches to requests method, even though is present in Bitbucket's session
<img width="2168" alt="Screenshot 2023-06-29 at 00 44 21" src="https://github.com/atlassian-api/atlassian-python-api/assets/1463733/3426eae0-914f-491d-95dc-88dc205689fb">

What I've tried so far:

- Creating a requests Session and passing it to Bitbucket's constructor
- Creating a requests Session and updating the Authorization header
- Pass username and password
- Recreating environment using Docker (got same error)

*Note: Using Postman with the same token works fine*

**Comment by davidmorabito** [comment]
Looks like it gets fixed by installing latest version of requests: 2.31.0
