### ISSUE TITLE
remove_page_history and remove_content_history_in_cloud fail

### ISSUE THREAD

**Issue by LucaMingarelli** [atlassian-api/atlassian-python-api#1238]
`remove_page_history` and `remove_content_history_in_cloud` fail with error

```
requests.exceptions.HTTPError: null for uri: 
```
 
When looking inside the module, the request returns a 404 status

**Comment by gonchik** [comment]
Hello @LucaMingarelli , 
could you share the logs please? 
looks like we need to wrap up a new version

**Comment by LucaMingarelli** [comment]
Hi @gonchik, by logs you mean the traceback? In case here below, but please let me know if you meant something else
 
```
Traceback (most recent call last):
  File "C:\Mambaforge\envs\Python3.11\Lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-df817a7ca8fb>", line 1, in <module>
    confluence.get_content_history_by_version_number(content_id=content_id, version_number=2)
  File "C:\Mambaforge\envs\Python3.11\Lib\site-packages\atlassian\confluence.py", line 1460, in get_content_history_by_version_number
    return self.get(url)
           ^^^^^^^^^^^^^
  File "C:\Mambaforge\envs\Python3.11\Lib\site-packages\atlassian\rest_client.py", line 285, in get
    response = self.request(
               ^^^^^^^^^^^^^
  File "C:\Mambaforge\envs\Python3.11\Lib\site-packages\atlassian\rest_client.py", line 257, in request
    self.raise_for_status(response)
  File "C:\Mambaforge\envs\Python3.11\Lib\site-packages\atlassian\confluence.py", line 3151, in raise_for_status
    raise HTTPError(error_msg, response=response)
requests.exceptions.HTTPError: null for uri: https://confluence.ecb.europa.eu/rest/api/content/247714020/version/2
confluence.remove_content_history_in_cloud(page_id=int(page_id), version_id=2)
Traceback (most recent call last):
  File "C:\Mambaforge\envs\Python3.11\Lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-314262664ece>", line 1, in <module>
    confluence.remove_content_history_in_cloud(page_id=int(page_id), version_id=2)
  File "C:\Mambaforge\envs\Python3.11\Lib\site-packages\atlassian\confluence.py", line 1494, in remove_content_history_in_cloud
    self.delete(url)
  File "C:\Mambaforge\envs\Python3.11\Lib\site-packages\atlassian\rest_client.py", line 449, in delete
    response = self.request(
               ^^^^^^^^^^^^^
  File "C:\Mambaforge\envs\Python3.11\Lib\site-packages\atlassian\rest_client.py", line 257, in request
    self.raise_for_status(response)
  File "C:\Mambaforge\envs\Python3.11\Lib\site-packages\atlassian\confluence.py", line 3151, in raise_for_status
    raise HTTPError(error_msg, response=response)
requests.exceptions.HTTPError: null for uri: https://confluence.ecb.europa.eu/rest/api/content/247701672/version/2

```

**Comment by LucaMingarelli** [comment]
For the record, I get the same also for 

```python
confluence.get_content_history_by_version_number(content_id=content_id, version_number=2)
```

**Comment by gonchik** [comment]
Added in major release
https://github.com/atlassian-api/atlassian-python-api/commit/616c58ee4f4c63ddb34635c494057f8fbe584ad7
