### ISSUE TITLE
requests.exceptions.ConnectTimeout

### ISSUE THREAD

**Issue by kurt-rhee** [atlassian-api/atlassian-python-api#1246]
Hello, 

I am attempting to read all of the issues within a given sprint.

```
import os
from dotenv import load_dotenv
from atlassian import Jira

load_dotenv()
jira = Jira(
    url='https://terabase.atlassian.com',
    username=os.getenv('EMAIL_ADDRESS'),
    password=os.getenv('API_TOKEN'),
    cloud=True
)
print('authentication complete')
issues = jira.get_all_issues_for_sprint_in_board(board_id=22, sprint_id=527)
```

When I run the code above I get the following exception:  

```
authentication complete
Traceback (most recent call last):
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\urllib3\connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x00000216B0FCC190>, 'Connection to terabase.atlassian.com timed out. (connect timeout=75)')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='terabase.atlassian.com', port=443): Max retries exceeded with url: /rest/agile/1.0/board/22/sprint/527/issue?validateQuery=True&maxResults=50 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000216B0FCC190>, 'Connection to terabase.atlassian.com timed out. (connect timeout=75)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1.3\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\krhee\PycharmProjects\jira-automation\main.py", line 5, in <module>
    from controllers import (
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\krhee\PycharmProjects\jira-automation\controllers\__init__.py", line 1, in <module>
    from controllers.groomed_priority_backlog import sort_groomed_priority_backlog
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\krhee\PycharmProjects\jira-automation\controllers\groomed_priority_backlog.py", line 26, in <module>
    issues = jira.get_all_issues_for_sprint_in_board(board_id=22, sprint_id=527)
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\atlassian\jira.py", line 4726, in get_all_issues_for_sprint_in_board
    return self.get(url, params=params)
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\atlassian\rest_client.py", line 288, in get
    response = self.request(
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\atlassian\rest_client.py", line 241, in request
    response = self._session.request(
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\krhee\PycharmProjects\jira-automation\venv\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='terabase.atlassian.com', port=443): Max retries exceeded with url: /rest/agile/1.0/board/22/sprint/527/issue?validateQuery=True&maxResults=50 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000216B0FCC190>, 'Connection to terabase.atlassian.com timed out. (connect timeout=75)')

```

**Comment by gonchik** [comment]
I hope you add incorrect domain.
Please use 
https://terabase.atlassian.net/   instaed https://terabase.atlassian.com/

**Comment by kurt-rhee** [comment]
@gonchik You are completely correct thank you!
