### ISSUE TITLE
[Bug] Confluence PDF Download Fails

### ISSUE THREAD

**Issue by julius-lange** [atlassian-api/atlassian-python-api#1450]
- Pipelines ingesting data from Confluence fail for me since 03/09/24
- I recreated the issue with `examples/confluence/confluence_export_page.py` with the following logs:

```
PDF conversion not successful.
Failed to get download PDF url.
Traceback (most recent call last):
  File "...", line 17, in <module>
    content = confluence.export_page(page_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\atlassian\confluence.py", line 2495, in export_page
    return self.get_page_as_pdf(page_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\atlassian\confluence.py", line 2474, in get_page_as_pdf
    raise ApiNotFoundError("Failed to export page as PDF", reason="Failed to get download PDF url.")
atlassian.errors.ApiNotFoundError: Failed to export page as PDF
```
- Might have something to do with `get_pdf_download_url_for_confluence_cloud` and how this in turn interacts with the `get` method of `atlassian/rest_client.py`
- Could this possible be due to a REST API change from Atlassian (I didn't find any)?
- I've recreated the bug with versions 3.36.0, 3.41.0, 3.41.11

**Comment by julius-lange** [comment]
Cannot reproduce the bug today
