### ISSUE TITLE
Behind corporate proxy

### ISSUE THREAD

**Issue by adriens** [atlassian-api/atlassian-python-api#251]
# Description

I'm under windows and behind a corporate proxy, with an on premise Jira instance. My worsktation is globally using a proxy, and in my case it causes a lot of trouble when I try to interact with the API.

```python
from atlassian import Jira

jira = Jira(
    url='https://jira.intranet.opt/',
    username='MY_LOGIN',
    password='MY_PASSWORD')

JQL = 'project = MYPROJECT AND status NOT IN (Closed, Resolved) ORDER BY issuekey'
data = jira.jql(JQL)
print(data)
```

Running this code leads me the following stacktrace :

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. Tous droits réservés.

PS C:\Users\MY_LOGIN> & C:/Python37/python.exe c:/Users/MY_LOGIN/Desktop/jira.py
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 597, in urlopen
    self._prepare_proxy(conn)
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 807, in _prepare_proxy
    conn.connect()
  File "C:\Python37\lib\site-packages\urllib3\connection.py", line 324, in connect
    self._tunnel()
  File "C:\Python37\lib\http\client.py", line 911, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 503 Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python37\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='jira.intranet.opt', port=443): Max retries exceeded with url: /rest/api/2/search?startAt=0&fields=%2Aall&jql=project+%3D+MYPROJECT+AND+status+NOT+IN+%28Closed%2C+Resolved%29+ORDER+BY+issuekey (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/MY_LOGIN/Desktop/jira.py", line 9, in <module>
    data = jira.jql(JQL)
  File "C:\Python37\lib\site-packages\atlassian\jira.py", line 79, in jql
    return self.get('rest/api/2/search', params=params)
  File "C:\Python37\lib\site-packages\atlassian\rest_client.py", line 173, in get
    trailing=trailing)
  File "C:\Python37\lib\site-packages\atlassian\rest_client.py", line 120, in request
    files=files
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python37\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='jira.intranet.opt', port=443): Max retries exceeded with url: /rest/api/2/search?startAt=0&fields=%2Aall&jql=project+%3D+MYPROJECT+AND+status+NOT+IN+%28Closed%2C+Resolved%29+ORDER+BY+issuekey (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable')))
```

# Action

Please explain how to programmatically tell to the `Python` script not to use local proxy settings (Internet Explorer's one).

Thank you in advance for your help. 🙏

**Comment by gonchik** [comment]
Hi! 
You can try this one:
https://stackoverflow.com/questions/17247981/how-to-tell-python-to-automatically-use-the-proxy-setting-in-windows-xp-like-rs?rq=1

Or implement wrapper for requests wrapper:
https://stackoverflow.com/questions/30692759/how-to-use-requests-post-with-proxy-authentication-in-python/30694179
https://stackoverflow.com/questions/13506455/how-to-pass-proxy-authentication-requires-digest-auth-by-using-python-requests

**Comment by adriens** [comment]
Thanks @gonchik  👍
