### ISSUE TITLE
Implement better error handling

### ISSUE THREAD

**Issue by bradphelan** [atlassian-api/atlassian-python-api#257]
For some reason the JIRA server is randomly throwing authentication errors. I'll take this up with my IT group. however the python API doesn't throw any exceptions it just returns a string of the html of the error. For example if I do
```
jira = Jira(
    url=host,
    username=user,
    password=passwd)

data = jira.jql(q)
```

if there is an auth error then data comes back as the string content of the html error from jira. It would be nice if the python api would just detect this internally and throw some kind of exception. Otherwise there is a cryptic error later on where I try to index the data structure and get a failure because it is not the correct type.

**Comment by gonchik** [comment]
Hi! 
Thanks for that, I am thinking to redesign exist handlers. 
It will be good if you provide more detail info, like logs etc. 
and your expectation as well

**Comment by tntC4stl3** [comment]
Agree, I think it's better to let the caller to decide how to handle those exceptions instead of only log in api library.

**Comment by tntC4stl3** [comment]
In my case, sometimes the IT changes the field attribute without notifying users, so it logs error in `atlassian-python-api`, but the caller doesn't know this is already failed.
![Screen Shot 2019-07-22 at 4 46 35 PM](https://user-images.githubusercontent.com/1506238/61619043-a9801880-aca0-11e9-864f-e5df60b5200f.png)

**Comment by Vanderhoof** [comment]
Also I would suggest to make responses more consistent.
For example:

* If I call `Confluence.get_page_by_id` and provide the wrong ID, i get a response dictionary with `statusCode` and `data` fields.
* If I call the same method with the correct ID — I only get the page dictionary, without any `statusCode` fields. So to check for errors I have to check if the `statusCode` field is in the dictionary first?
* Next, if I call the same method, but it turns out that the login or password provided were incorrect. In this case I will always get a string with error page HTML. So it means that first I have to check that the type of the response, and then look for `statusCode`? That seems a bit wrong.

Maybe there are some other reponse options, I just started using the lib.

I think (I may not know everything) that it would be best to always have similar response dictionary structure with `statusCode` always present for easy error checking. I imagine that changing the working logic (in my example when the id was provided correctly) would be painful for users, because they've already have a lot of code using the old structure. But at least it should be possible to make all error responses consistent. Especially because the string with error page I got in the last scenario had an HTTP status code and error message written inside.

**Comment by tbugfinder** [comment]
I'd like to second that this python-lib should raise exceptions if the server returns an error.

**Comment by LudovicRousseau** [comment]
Returning an exception for errors would be fine and in the Python spirit.

Another option is to provide a `check_for_error()` method so that you can do something like:
```
status = confluence.update_page(page_id, title, body)
if confluence.check_for_error(status):
    # handle the error
```

I use this specific example because now the dictionary returned by `confluence.update_page()` does NOT contain a `statusCode` key any more. I don't think I changed something on my side. Maybe the server was updated.

**Comment by gonchik** [comment]
Hi! 
 what do you think implement the exceptions.py with class AtlassinError( ) or with inherits https://github.com/psf/requests/blob/master/requests/exceptions.py

**Comment by rlmaers** [comment]
What about just propagating any exceptions raised by the `raise_for_status` method in the response? Following is a suggestion based on the last part of  the `AtlassianRestAPI.request` method.
```
def request(self, method='GET', path='/', data=None, flags=None, params=None, headers=None,
            files=None, trailing=None):
    [...]
    if self.advanced_mode:
        self.response = response
        return response
    try:
        if response.text:
            response_content = response.json()
        else:
            response_content = response.content
    except ValueError:
        response_content = response.content
    if response.status_code == 200:
        log.debug('Received: {0}\n {1}'.format(response.status_code, response_content))
    elif response.status_code == 201:
        log.debug('Received: {0}\n "Created" response'.format(response.status_code))
    elif response.status_code == 204:
        log.debug('Received: {0}\n "No Content" response'.format(response.status_code))
    elif response.status_code == 400:
        log.error('Received: {0}\n Bad request \n {1}'.format(response.status_code, response_content))
    elif response.status_code == 401:
        log.error('Received: {0}\n "UNAUTHORIZED" response'.format(response.status_code))
    elif response.status_code == 404:
        log.error('Received: {0}\n Not Found'.format(response.status_code))
    elif response.status_code == 403:
        log.error('Received: {0}\n Forbidden. Please, check permissions'.format(response.status_code))
    elif response.status_code == 405:
        log.error('Received: {0}\n Method not allowed'.format(response.status_code))
    elif response.status_code == 409:
        log.error('Received: {0}\n Conflict \n '.format(response.status_code, response_content))
    elif response.status_code == 413:
        log.error('Received: {0}\n Request entity too large'.format(response.status_code))
    else:
        log.debug('Received: {0}\n {1}'.format(response.status_code, response))
        self.log_curl_debug(method=method, path=path, headers=headers, data=data, level=logging.DEBUG)
        log.error(response_content)
        try:
            response.raise_for_status()
        except requests.exceptions.HTTPError as err:
            log.error("HTTP Error occurred")
            log.error('Response is: {content}'.format(content=err.response.content))
    return response
```
The current error handling (above) could log all transactions and propagate any errors as following (below).
```
def request(self, method='GET', path='/', data=None, flags=None, params=None, headers=None,
            files=None, trailing=None):
    [...]
    if self.advanced_mode:
        return response

    try:
        response.raise_for_status()
    finally:
        log.debug(
            f'Received response HTTP {reponse.status_code} {response.reason}'
            'for request HTTP {method} {path}'
        )

    return response
```
It could at least be a starting point, and more specific errors related to the Atlassian products and the REST API could be wrapped in custom exception classes.

**Comment by gonchik** [comment]
Looks like it's good idea, than I was wondering it can be wrapped response status code and reason from docs as response.reason is  custom info from doc or source code (https://docs.atlassian.com/software/jira/docs/api/REST/8.5.3/#api/2-getAllPermissions).

**Comment by rlmaers** [comment]
You would like to incorporate Atlassian specific errors into the raised exception, right? For instance making it clear that a HTTP 403 response on a GET /rest/api/2/permissions request really means that the user doesn't have administrative privileges?

If so, then I suggest making a base exception class such as AtlassianException or similar, and a subclass exception for all of the different types of errors that can occur. Using the example above, let's say we have an exception class AtlassianPermissionError that is subclassed from AtlassianException. The `get_all_permissions` method in the Jira module could then be rewritten to the following in order to translate and convey the correct meaning of the HTTP 403 response.
```
diff --git a/atlassian/jira.py b/atlassian/jira.py
index 8e332f0..ac93097 100644
--- a/atlassian/jira.py
+++ b/atlassian/jira.py
@@ -1525,7 +1525,13 @@ class Jira(AtlassianRestAPI):
         :return: All permissions
         """
         url = 'rest/api/2/permissions'
-        return self.get(url)
+        try:
+            return self.get(url)
+        except requests.exception.HTTPError as err:
+            if err.response.status_code == 403:
+                raise AtlassianPermissionError("User doesn't have administrative privileges") from err
+
+            raise

     def get_all_permissionschemes(self, expand=None):
         """
```
The advantages of doing it this way is that the original exception is preserved and that the correct information (i.e. lacking administrative privileges) is conveyed to the user and/or developer. The disadvantage is that exception chaining requires Python 3. However, as Python 2 is EOL, I assume this isn't a problem.

**Comment by rlmaers** [comment]
I've made pull request #447 to show how these changes would look like for the Confluence module. I'll test the changes myself, but I'm also curious as to what you think.

**Comment by rlmaers** [comment]
It's been a while since I made the pull request. Any comments?

For what's it worth, I can at least confirm that it's far easier to handle errors in my own application.

**Comment by gonchik** [comment]
Hi!
@rlmaers Unfortunately, I still did not check the behaviour.
as example, that step is needful for sometimes you can copy and set password and do double check. 
self.log_curl_debug(method=method, path=path, headers=headers, data=data, level=logging.DEBUG)

**Comment by rlmaers** [comment]
Hi again!

What kind of behavior would you like to check?

I'm using 1.15.2 with the changes in the pull request applied in my application. For reasons unbeknownst to me, the Confluence instance that I'm working towards throws HTTP 5xx server errors back at me sometimes. I'm not at liberty to find and fix the underlying issue, but a simple workaround is to retry the API request in question. So, with the changes in the pull request, I've subclassed the Confluence class from the library and overloaded some of the methods.
```
def update_or_create(self, parent_id, title, body, representation="storage", minor_edit=False):
    attempt = 1
    while True:
        try:
            return super().update_or_create(
                parent_id, title, body, representation, minor_edit
            )
        except requests.HTTPError as err:
            if RETRY_ATTEMPTS < attempt:
                raise
            if err.response.status_code < 500:
                raise

            log.warning(
                f"HTTPError - {err.response.status_code} - {title} - Retrying ({attempt} / {RETRY_ATTEMPTS})"
            )
            time.sleep(RETRY_PAUSE)
            attempt += 1
```
In the example above, I'm catching any HTTP 5xx responses and retrying until the request goes through successfully or the number of retry attempts has been exhausted. This would be much more difficult to handle without the changes in the pull request, and I've not experienced any other errors related to the changes.

**Comment by ganeshaf** [comment]
Any idea when this error handling will be fixed. 

i'm facing the same issue. Below is the portion output.

```
ERROR:atlassian.rest_client:Received: 401
 "UNAUTHORIZED" response
ERROR:atlassian.rest_client:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/root/system_config/system_config.py", line 411, in <module>
    main()
  File "/root/system_config/system_config.py", line 370, in main
    space, parent_page_id = get_parent_page_id_and_space(conf, parent_page_link, logger)
  File "/root/system_config/system_config.py", line 74, in get_parent_page_id_and_space
    parent_page_id = confluence.get_page_id(space=space, title=parent_page_title)
  File "/usr/local/lib/python3.7/site-packages/atlassian/confluence.py", line 87, in get_page_id
    return (self.get_page_by_title(space, title) or {}).get('id')
  File "/usr/local/lib/python3.7/site-packages/atlassian/confluence.py", line 151, in get_page_by_title
    response = (self.get(url, params=params) or {}).get('results')
AttributeError: 'str' object has no attribute 'get'
```

**Comment by gonchik** [comment]
I hope after skipping  python2 and using extensively f-strings.
And errors.py will be extended and used for error handling. 
Feel free to contribute into the class
