### ISSUE TITLE
[BUG] confluence.get_page_space() gives error

### ISSUE THREAD

**Issue by ResourceHog** [atlassian-api/atlassian-python-api#325]
Traceback (most recent call last):
  File "pythoncli.py", line 7, in <module>
    print(confluence.get_page_space(271332973))
  File "/site-packages/atlassian/confluence.py", line 103, in get_page_space
    return ((self.get_page_by_id(page_id, expand='space') or {}).get('space') or {}).get('key')
AttributeError: 'str' object has no attribute 'get'

**Comment by ResourceHog** [comment]
This was caused by entering an invalid end point.
