### ISSUE TITLE
Confluence SSL Certification Error

### ISSUE THREAD

**Issue by jakecurrant** [atlassian-api/atlassian-python-api#419]
Hi, 
I'm attempting to use this to interface with an internal Confluence system and although I have python correctly interacting through the proxy via environment variables I still get the following stacktrace:

Traceback (most recent call last):
  File "C:\dev\WinPython-64bit-3720\python-3.7.2.amd64\lib\site-packages\urllib3\connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "C:\dev\WinPython-64bit-3720\python-3.7.2.amd64\lib\site-packages\urllib3\connectionpool.py", line 805, in _prepare_proxy
    conn.connect()
  File "C:\dev\WinPython-64bit-3720\python-3.7.2.amd64\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "C:\dev\WinPython-64bit-3720\python-3.7.2.amd64\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\dev\WinPython-64bit-3720\python-3.7.2.amd64\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\dev\WinPython-64bit-3720\python-3.7.2.amd64\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\dev\WinPython-64bit-3720\python-3.7.2.amd64\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

Is there any way I can have the module pointed directly at my local certificates or is there a workaround? 
In this case I do not have the luxury of being able to disable SSL verification.

Thanks.

**Comment by gonchik** [comment]
Hi!
Do you mean set as parameters for session and disable verify ssl 
https://stackoverflow.com/questions/15445981/how-do-i-disable-the-security-certificate-check-in-python-requests ?

Cheers,
Gonchik

**Comment by gonchik** [comment]
confluence = Confluence(
    url=CONFLUENCE_URL,
    username=ATLASSIAN_USER,
    password=ATLASSIAN_PASSWORD,
    verify_ssl=False)
