### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'get'

### ISSUE THREAD

**Issue by dj-wasabi** [atlassian-api/atlassian-python-api#484]
Hi,

I try to get the very first few things working, but I immediately run into an error.

Did an:
```
pip install atlassian-python-api
```
to install the module. So this is the version installed on my Mac:

```
└─[$] <git:(master*)> pip freeze | grep atlassian-python-api
atlassian-python-api==1.15.6
```

I use this code, as used in the readme:
```
from atlassian import Bitbucket
bitbucket = Bitbucket(
    url='https://bitbucket.org',
    username='my_username',
    password='my_password')

data = bitbucket.project_list()
print(data)
```
Error:
```
Traceback (most recent call last):
  File "./bin/bb-repositories.py", line 27, in <module>
    data = bitbucket.project_list()
  File "/Users/wdijkerman/.virtualenvs/python2/lib/python2.7/site-packages/atlassian/bitbucket.py", line 22, in project_list
    return (self.get('rest/api/1.0/projects', params=params) or {}).get('values')
AttributeError: 'unicode' object has no attribute 'get'
```

What am I doing wrong?

**Comment by dj-wasabi** [comment]
I have the (almost) same issue with python 3:

```
Traceback (most recent call last):
  File "./bin/bb-repositories.py", line 27, in <module>
    data = bitbucket.project_list()
  File "/Users/wdijkerman/.virtualenvs/python3/lib/python3.7/site-packages/atlassian/bitbucket.py", line 22, in project_list
    return (self.get('rest/api/1.0/projects', params=params) or {}).get('values')
AttributeError: 'str' object has no attribute 'get'
```

**Comment by GaAdam** [comment]
I;ve got exactly the same issue with python3:

`File "new_repo_bitbucket.py", line 29, in <module>
    a=bitbucket.repo_list("PROJ")
  File "F:\Python\lib\site-packages\atlassian\bitbucket.py", line 475, in repo_list
    if response.get('isLastPage'):
AttributeError: 'str' object has no attribute 'get'`

**Comment by dj-wasabi** [comment]
I updated to latest version right now and don't see this problem anymore.

```
atlassian-python-api==1.16.0
```
