### ISSUE TITLE
get_issue_transition fails with advanced_mode on

### ISSUE THREAD

**Issue by m-stolle** [atlassian-api/atlassian-python-api#501]
`self.get_issue_transitions_full(issue_key) or {}` does not work with ReponseObject, therefore we get an AttributeError if advanced_mode is used.

```
    def get_issue_transitions(self, issue_key):
        return [{'name': transition['name'], 'id': int(transition['id']), 'to': transition['to']['name']}
                for transition in (self.get_issue_transitions_full(issue_key) or {}).get('transitions')]
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\aie\lib\site-packages\atlassian\jira.py", line 1229, in issue_transition
    return self.set_issue_status(issue_key, status)
  File "C:\ProgramData\Anaconda3\envs\aie\lib\site-packages\atlassian\jira.py", line 1233, in set_issue_status
    transition_id = self.get_transition_id_to_status_name(issue_key, status_name)
  File "C:\ProgramData\Anaconda3\envs\aie\lib\site-packages\atlassian\jira.py", line 1224, in get_transition_id_to_status_name
    for transition in self.get_issue_transitions(issue_key):
  File "C:\ProgramData\Anaconda3\envs\aie\lib\site-packages\atlassian\jira.py", line 1193, in get_issue_transitions
    for transition in (self.get_issue_transitions_full(issue_key) or {}).get('transitions')]
AttributeError: 'Response' object has no attribute 'get'
```

**Comment by gonchik** [comment]
https://github.com/atlassian-api/atlassian-python-api/commit/2b7c3560ca15901b53af4ed794f0a42f629d37a3

**Comment by gonchik** [comment]
it has been fixed long time ago
