### ISSUE TITLE
[Bitbucket] Working with bitbucket.org

### ISSUE THREAD

**Issue by sechastain** [atlassian-api/atlassian-python-api#504]
Hi -

I've been stumbling for a couple of hours trying to get this API to work with:
- https://bitbucket.org
- an app username and password
- listing repos in an account other than my own (/otheraccount/repo vs /myaccount/repo)

I'm sure I'm missing something in the docs - but honestly, I've poured through them and stared at code and am getting nowhere.

Could you help me with a quick example?

What I'm working with right now:

```
from atlassian import Bitbucket

def readCredentials():
  lines = None
  with open('.credentials', 'r') as f:
    lines = f.readlines()

  return [l.strip() for l in lines]

creds = readCredentials()
bb = Bitbucket(url='https://bitbucket.org', username=creds[0], password=creds[1])

projs = bb.project_list()

for p in projs:
  print(p)
  print(p.repo_list())
```

**Comment by sechastain** [comment]
Decided I'd go lower level, as it doesn't look like this API has the support I need.

First thing I had to do was generate a consumer key.  I placed the values into a .credentials file.

Wrote the following code - seems to be working:

```
def readCredentials():
  lines = None
  with open('.credentials', 'r') as f:
    lines = f.readlines()
  return [l.strip() for l in lines]

def startBBSession(client_id, client_secret):
    auth = HTTPBasicAuth(client_id, client_secret)
    client = BackendApplicationClient(client_id=client_id)
    oauth = OAuth2Session(client=client)
    token = oauth.fetch_token(token_url='https://bitbucket.org/site/oauth2/access_token', auth=auth)
    return (oauth, token)

def getRepos(sess, page=1, url=None):
  suff = '&page=' + str(page) if page > 1 else ''
  url = url if url is not None else ('https://api.bitbucket.org/2.0/repositories/myrepos?pagelen=100' + suff)
  return sess.get(url).json()

creds = readCredentials()

(sess, token) = startBBSession(*creds[0:2])

pg = getRepos(sess)
```

Hopefully this will be useful to this project or anyone else banging their head on the problem

**Comment by SLRover** [comment]
Hi @sechastain,

Thanks for your request.

Bitbucket team changed REST API for the Cloud. And some methods deprecated. For example **project_list()**. Because new REST API doesn't have projects. It has workspaces.

We working on changing our wrapper.

**Comment by dj-wasabi** [comment]
@SLRover 

Any idea when this is done? I have this issue right now:

```
Traceback (most recent call last):
  File "./bin/bb-repositories.py", line 27, in <module>
    data = bitbucket.project_list()
  File "/Users/wdijkerman/.virtualenvs/python2/lib/python2.7/site-packages/atlassian/bitbucket.py", line 23, in project_list
    return (self.get('rest/api/1.0/projects', params=params) or {}).get('values')
  File "/Users/wdijkerman/.virtualenvs/python2/lib/python2.7/site-packages/atlassian/rest_client.py", line 177, in get
    trailing=trailing)
  File "/Users/wdijkerman/.virtualenvs/python2/lib/python2.7/site-packages/atlassian/rest_client.py", line 161, in request
    response.raise_for_status()
  File "/Users/wdijkerman/.virtualenvs/python2/lib/python2.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://bitbucket.org/rest/api/1.0/projects
```

With this:
```
bitbucket = Bitbucket(
    url='https://bitbucket.org',
    username=username,
    password=password)
```

So I think I need to wait on the change?

**Comment by gonchik** [comment]
@sechastain Feel free to make a PR with your examples. 
Meanwhile added the additional checker.
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/bitbucket.py#L16
