### ISSUE TITLE
[Jira] Difficulty debugging HTTP 400 errors.

### ISSUE THREAD

**Issue by jkodroff** [atlassian-api/atlassian-python-api#510]
When making a call to `jira.issue_create`, the library throws an exception when the request is invalid like the following:

```
Traceback (most recent call last):
  File "migrate_migration_board.py", line 128, in <module>
    resp = jira.issue_create(fields=subtask_fields)
  File "/Users/jkodroff/Library/Caches/pypoetry/virtualenvs/excel-to-jira-lAm77rlV-py3.8/lib/python3.8/site-packages/atlassian/jira.py", line 1047, in issue_create
    return self.post(url, data={'fields': fields})
  File "/Users/jkodroff/Library/Caches/pypoetry/virtualenvs/excel-to-jira-lAm77rlV-py3.8/lib/python3.8/site-packages/atlassian/rest_client.py", line 192, in post
    response = self.request('POST', path=path, data=data, headers=headers, files=files, params=params,
  File "/Users/jkodroff/Library/Caches/pypoetry/virtualenvs/excel-to-jira-lAm77rlV-py3.8/lib/python3.8/site-packages/atlassian/rest_client.py", line 161, in request
    response.raise_for_status()
  File "/Users/jkodroff/Library/Caches/pypoetry/virtualenvs/excel-to-jira-lAm77rlV-py3.8/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://REDACTED.atlassian.net/rest/api/2/issue
```

I'm guessing that the response from the JIRA server contains a more detailed error message in the response, which would help me debug the actual problem, but I can't figure out how to access the response body.

Could you provide an example on how to get additional information out of the exception?

**Comment by jkodroff** [comment]
To answer my own question:

```python
from requests import HTTPError

try:
  jira.issue_create(fields)
except HTTPError as ex:
  print(f'Error creating issue.  Details:\n{ex.response.text}')
```

If possible though, would be good to make this more obvious to users of this library.  It's a little awkward IMO that we'd have to know the specific structure of an exception class from another library (Requests).  That said, I'm incredibly grateful this library exists - by far the best Atlassian client I've seen.

**Comment by gonchik** [comment]
Hi! 
For now I just wrap into Exception the errors
https://github.com/atlassian-api/atlassian-python-api/commit/087711958cf88255bf7519d9459526d2260a0895
