### ISSUE TITLE
'ApiValueError' object is not callable when 400 returned

### ISSUE THREAD

**Issue by davendu** [atlassian-api/atlassian-python-api#513]
Following error happened:

```
Traceback (most recent call last):
  File "/data/home/davendu/miniconda3/envs/wiki_import/lib/python3.8/site-packages/atlassian/confluence.py", line 1058, in update_page
    response = self.put('rest/api/content/{0}'.format(page_id), data=data)
  File "/data/home/davendu/miniconda3/envs/wiki_import/lib/python3.8/site-packages/atlassian/rest_client.py", line 203, in put
    response = self.request('PUT', path=path, data=data, headers=headers, files=files, params=params,
  File "/data/home/davendu/miniconda3/envs/wiki_import/lib/python3.8/site-packages/atlassian/rest_client.py", line 161, in request
    response.raise_for_status()
  File "/data/home/davendu/miniconda3/envs/wiki_import/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://wiki.local/rest/api/content/1302093

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "do.py", line 94, in main
    w.update_or_create(parent_id=parent_id, title=title,
  File "/data/home/davendu/miniconda3/envs/wiki_import/lib/python3.8/site-packages/atlassian/confluence.py", line 1191, in update_or_create
    result = self.update_page(parent_id=parent_id, page_id=page_id, title=title, body=body,
  File "/data/home/davendu/miniconda3/envs/wiki_import/lib/python3.8/site-packages/atlassian/confluence.py", line 1061, in update_page
    raise ApiValueError(
TypeError: 'ApiValueError' object is not callable
```

I checked the commit log and found the commit dc0917f3e76834d681c3e5a794fb4a671002288c  is the root cause. For example:

```
@@ -212,7 +212,7 @@ def get_page_by_id(self, page_id, expand=None, status=None, version=None):
                 raise ApiError(
                     "There is no content with the given id, "
                     "or the calling user does not have permission to view the content"
-                ) from e
+                )(e)
 
             raise
```

The original `raise...from...` syntax supported by Python 3 is replaced to this strange format, which is neither supported by Python 2 nor Python 3:

```
➜ python3 -c 'raise ValueError("test")(EnvironmentError("nope"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'ValueError' object is not callable


➜ python2 -c 'raise ValueError("test")(EnvironmentError("nope"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'exceptions.ValueError' object is not callable

➜ python3 -c 'raise ValueError("test") from EnvironmentError("nope")'
OSError: nope

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: test
```

Should we return an function instead of `Exception` object for `APIError` class? Or we should just drop support for Python 2? Considering it has already been discouraged to use.

**Comment by gonchik** [comment]
Hi! 
That's pretty interesting question, 
at the moment I have many scripts still on python2 on servers. That's bad to stop support. 
But in long term correct way is stopping to support Python2

Cheers,
Gonchik Tsymzhitov

**Comment by gonchik** [comment]
Hi!
@davendu looks good :) 
What about a PR ?

**Comment by davendu** [comment]
@gonchik 

> What about a PR ?

Sorry for high latency ;-) but done in #516.

But I did not have time to test it under Python 2. You may want to run `examples/confluence/confluence-nested-error.py` for a quick test.
