### ISSUE TITLE
Logs not showing up

### ISSUE THREAD

**Issue by isaac-philip** [atlassian-api/atlassian-python-api#525]
Please provide some guidance as to this.

Why does the _error logs or any logs_ for that matter not show up.

Any specific configuration required through terminal?

So I am using it directly in the **Python REPL** and do not see logs.

_The following example demonstrates how the exception is raised but what needs to be improved is not conveyed through logs._

```python
>>> fields = dict(summary='Summary Data', project=dict(key='APA') )
>>> jira.create_issue(fields=fields)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/atlassian-python-api/atlassian/jira.py", line 1055, in create_issue
    return self.post(url, params=params, data=data)
  File "/atlassian-python-api/atlassian/rest_client.py", line 193, in post
    trailing=trailing)
  File "/atlassian-python-api/atlassian/rest_client.py", line 161, in request
    response.raise_for_status()
  File "/venv_git_atlassian-python-api/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://123.atlassian.net/rest/api/2/issue?updateHistory=false
```

I maybe missing something so please help out and we can take the conversation ahead.

**Comment by isaac-philip** [comment]
What this is causing trouble is that I cannot view the actual reason the call failed.

**Comment by harryharpel** [comment]
Not sure if this will fix your problem as I have not used this function personally, but in the documentation for jira.create_issue it says the fields parameter has the mandatory keys issuetype, summary, and project. I noticed in your fields parameter you did not include an issuetype. This is the example they included:

```
fields = dict(
  summary='Into The Night',
  project = dict(key='APA'),
  issuetype = dict(name='Story')
)
jira.create_issue(fields=fields)
```

**Comment by isaac-philip** [comment]
@harryharpel 

yea, well the documentation in that function was added by me so I am aware 💯 

Actually what I wanted to highlight was that the reason for the Error is not displayed which can aid in user formatting the payload/fields to retry.

**Comment by gonchik** [comment]
You can configure like this
https://github.com/atlassian-api/atlassian-python-api/blob/master/examples/jira/jira_admins_confluence_page.py#L7

if you need more log eel free to send PR with adjusted log lines
