### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by masics** [atlassian-api/atlassian-python-api#541]
I get an error `AttributeError: 'str' object has no attribute 'get'` with following stack:
```
Traceback (most recent call last):
  File "confluence_projects_dashboard.py", line 261, in <module>
    main()
  File "confluence_projects_dashboard.py", line 212, in main
    parse_dir(pargs.location)
  File "confluence_projects_dashboard.py", line 220, in parse_dir
    main_page_id = confluence.get_page_id(SPACENAME, MAINPAGE)
  File "/projects/confluence/venv/lib/python3.8/site-packages/atlassian/confluence.py", line 87, in get_page_id
    return (self.get_page_by_title(space, title) or {}).get('id')
  File "/projects/confluence/venv/lib/python3.8/site-packages/atlassian/confluence.py", line 151, in get_page_by_title
    return (self.get(url, params=params) or {}).get('results')[0]
AttributeError: 'str' object has no attribute 'get'
```
What is that and how to fix it?

**Comment by gonchik** [comment]
Could you run in debug mode, please? 
Just interesting what exactly it was

**Comment by masics** [comment]
How I do that?

**Comment by gonchik** [comment]
Please, add into your code the next lines 

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by masics** [comment]
I've added logging and will report when it will happen again.

**Comment by gonchik** [comment]
Thank you

**Comment by gonchik** [comment]
Close as Obsolete
