### ISSUE TITLE
[Confluence] cannot import name 'Confluence'

### ISSUE THREAD

**Issue by sandeepjawalkar** [atlassian-api/atlassian-python-api#636]
Dear team,
Last month I was able to use this module without any error, but I have got this error today
```
Traceback (most recent call last):
  File "getPlannedStory.py", line 1, in <module>
    from atlassian import Confluence
  File "/home/sandeep.jawalkar/.local/lib/python2.7/site-packages/atlassian/__init__.py", line 1, in <module>
    from .bamboo import Bamboo
  File "/home/sandeep.jawalkar/.local/lib/python2.7/site-packages/atlassian/bamboo.py", line 4, in <module>
    from requests.exceptions import HTTPError
  File "/home/sandeep.jawalkar/.local/lib/python2.7/site-packages/requests/__init__.py", line 120, in <module>
    from . import utils
  File "/home/sandeep.jawalkar/.local/lib/python2.7/site-packages/requests/utils.py", line 27, in <module>
    from ._internal_utils import to_native_string
  File "/home/sandeep.jawalkar/.local/lib/python2.7/site-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/home/sandeep.jawalkar/.local/lib/python2.7/site-packages/requests/compat.py", line 43, in <module>
    import cookielib
  File "/usr/lib/python2.7/cookielib.py", line 32, in <module>
    import re, urlparse, copy, time, urllib
  File "/home/sandeep.jawalkar/workspace/2020/11/25_11_2020/TDMLMSYNC/backend/copy.py", line 1, in <module>
    """Generic (shallow and deep) copying operations.
ImportError: cannot import name Confluence
```
I have not done any changes,
I have tried reinstalling , but the same issue is coming

**my sample code** 
```
from atlassian import Confluence

confluence = Confluence(
    url='http://localhost:8090',
    username='admin',
    password='admin')

status = confluence.move_page(space_key, page_id, target_title, position="append")
print(status)
```

could you please help me

**Comment by sandeepjawalkar** [comment]
Dear team,
Issue is solved,
Sorry to raise issue,
its because of junk file copy.py.
