### ISSUE TITLE
get_page_by_id method Use macro timeout,  Need to set timeout

### ISSUE THREAD

**Issue by monkey-wenjun** [atlassian-api/atlassian-python-api#639]
username and password ok ,404 appear frequently

```

 File "atlassian/confluence.py", line 260, in get_page_by_id
  File "atlassian/rest_client.py", line 264, in get
  File "atlassian/rest_client.py", line 228, in request
  File "requests/models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://doc.qima-inc.com/rest/api/content/268034221?expand=body.view

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "active_data_setting.py", line 82, in get_dake_table
    body = self.cf.get_page_by_id(268034221, expand="body.view")
  File "atlassian/confluence.py", line 267, in get_page_by_id
atlassian.errors.ApiError: There is no content with the given id, or the calling user does not have permission to view the content

During handling of the above exception, another exception occurred:



fix

             def get_page_by_id(self, page_id, expand=None, status=None, version=None):
        """
        Returns a piece of Content.
        Example request URI(s):
        http://example.com/confluence/rest/api/content/1234?expand=space,body.view,version,container
        http://example.com/confluence/rest/api/content/1234?status=any
        :param page_id: Content ID
        :param status: (str) list of Content statuses to filter results on. Default value: [current]
        :param version: (int)
        :param expand: OPTIONAL: Default value: history,space,version
                       We can also specify some extensions such as extensions.inlineProperties
                       (for getting inline comment-specific properties) or extensions.resolution
                       for the resolution status of each comment in the results
        :return:
        """
        params = {}
        if expand:
            params["expand"] = expand
        if status:
            params["status"] = status
        if version:
            params["version"] = version
        url = "rest/api/content/{page_id}".format(page_id=page_id)

        try:
            response = self.get(url, params=params, timeout=60)
        except HTTPError as e:
            if e.response.status_code == 404:
                # Raise ApiError as the documented reason is ambiguous
                raise ApiError(
                    "There is no content with the given id, "
                    "or the calling user does not have permission to view the content",
                    reason=e,
                )

            raise

        return response


```

![](https://file.awen.me/blog/20201130203910.png)

**Comment by Spacetown** [comment]
Can you create a PR for this? It will be easier to see your change there.

**Comment by gonchik** [comment]
@monkey-wenjun  you can set the timeout into object. 

`
confluence = Confluence(url="http://localhost:8090", username="admin", password="admin", timeout=185)
`

**Comment by gonchik** [comment]
Extended the timeout globally, because at the moment I am experiencing the slow connectivity with Atlassian cloud
https://github.com/atlassian-api/atlassian-python-api/commit/231eb5d368321fee4db6f79ae6fdfa2c82d32203
