### ISSUE TITLE
Jira - Encoding error retrieving issues

### ISSUE THREAD

**Issue by graydryan** [atlassian-api/atlassian-python-api#759]
Having issue retrieving Jira Issue.  This seems to be an issue with ASCII and UTF-8 encoding.

Code:

```
from atlassian import Jira

jira = Jira(
    url='https://instance.atlassian.net',
    username='user@domain.com',
    password='token',
    cloud=True)

JQL = 'project = FL'
data = jira.jql(JQL)

summary = jira.issue(key = "SVC-187", fields = ["issuetype", "status", "summary"])

print(summary)
```

Error

`Traceback (most recent call last):
  File "test.py", line 10, in <module>
    data = jira.jql(JQL)
  File "/home/parallels/.local/lib/python2.7/site-packages/atlassian/jira.py", line 2271, in jql
    return self.get("rest/api/2/search", params=params)
  File "/home/parallels/.local/lib/python2.7/site-packages/atlassian/rest_client.py", line 272, in get
    absolute=absolute,
  File "/home/parallels/.local/lib/python2.7/site-packages/atlassian/rest_client.py", line 232, in request
    log.debug("HTTP: Response text -> {}".format(response.text))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 193089: ordinal not in range(128)
`

**Comment by isaac-philip** [comment]
is python 2.7 a necessity or can we try python3.7 and see if the issue occurs there too ?

**Comment by gonchik** [comment]
Now only python3
